<script type="text/html" id="site-card">

  <div class="sample-card">
    <table border="1">
      <tr>
        <td colspan="2" class="title-item">
          <h4 id="title">UDEMY : Projects in HTML5</h4>
        </td>
      </tr>
      <tr>
        <td colspan="2" class="description-item">
          <h4 id="description">Example using Canvas in HTML5</h4>
        </td>
      </tr>
      <tr>
        <td><h4>Links</h4></td>
        <td class="links-item">
            <ul id="links">
              <li>http://yoga.com</li>
            </ul>
        </td>
      </tr>
      <tr>
        <td><h4>Tags</h4></td>
        <td class="tags-item">
          <ul id="tags">
            <li>HTML5</li>
          </ul>
        </td>
      </tr>
    </table>
  </div>

</script>
