<script type="text/html" id="site-card">

  <div class="sample-card">
    <table border="1">
      <tr>
        <td colspan="2" class="title-item">
          <h4 id="title"></h4>
        </td>
      </tr>
      <tr>
        <td colspan="2" class="description-item">
          <h4 id="description"></h4>
        </td>
      </tr>
      <tr>
        <td><h4>Links</h4></td>
        <td class="links-item">
            <ul id="links">
            </ul>
        </td>
      </tr>
      <tr>
        <td><h4>Tags</h4></td>
        <td class="tags-item">
          <ul id="tags">
          </ul>
        </td>
      </tr>
    </table>
  </div>

</script>
